inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
  DisplayCopNames: true
  ExtraDetails: true
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
